//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftedSolutions.MarBasGleaner.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpAuthenticationHandlerL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpAuthenticationHandlerL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftedSolutions.MarBasGleaner.UI.HttpAuthenticationHandlerL10n", typeof(HttpAuthenticationHandlerL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If login window won&apos;t open, click &lt;a href=&apos;{0}&apos; target=&apos;worker&apos; onclick=&apos;worker=openWorker();return false;&apos;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string HintPopupBlocker {
            get {
                return ResourceManager.GetString("HintPopupBlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login complete, you may close this window..
        /// </summary>
        internal static string MsgComplete {
            get {
                return ResourceManager.GetString("MsgComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing authorization....
        /// </summary>
        internal static string MsgProcessing {
            get {
                return ResourceManager.GetString("MsgProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for login to complete....
        /// </summary>
        internal static string MsgWaiting {
            get {
                return ResourceManager.GetString("MsgWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Authorization Receiver.
        /// </summary>
        internal static string TitleAuthProcessor {
            get {
                return ResourceManager.GetString("TitleAuthProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Login Controller.
        /// </summary>
        internal static string TitleLoginController {
            get {
                return ResourceManager.GetString("TitleLoginController", resourceCulture);
            }
        }
    }
}
