//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftedSolutions.MarBasGleaner.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CleanUpCmdL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleanUpCmdL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftedSolutions.MarBasGleaner.Commands.CleanUpCmdL10n", typeof(CleanUpCmdL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall we correct checkpoint errors?.
        /// </summary>
        internal static string AskCorrectCheckpointErrors {
            get {
                return ResourceManager.GetString("AskCorrectCheckpointErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove grain {0:D} ({1}) from snapshot?.
        /// </summary>
        internal static string AskDeleteGrain {
            get {
                return ResourceManager.GetString("AskDeleteGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} is missing in the snapshot, pull it from the broker?.
        /// </summary>
        internal static string AskPullMissingGrain {
            get {
                return ResourceManager.GetString("AskPullMissingGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the grain to current checkpoint.
        /// </summary>
        internal static string ChoiceAddGrain {
            get {
                return ResourceManager.GetString("ChoiceAddGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the snapshot grain.
        /// </summary>
        internal static string ChoiceDeleteGrain {
            get {
                return ResourceManager.GetString("ChoiceDeleteGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string ChoiceNoop {
            get {
                return ResourceManager.GetString("ChoiceNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull the grain (if exists) from the broker into snapshot.
        /// </summary>
        internal static string ChoicePullGrain {
            get {
                return ResourceManager.GetString("ChoicePullGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleans up snapshot directory (correcting checkpoints, deleting orphans, pulling missing grains etc.).
        /// </summary>
        internal static string CmdDesc {
            get {
                return ResourceManager.GetString("CmdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unattended mode requires stored broker credentials.
        /// </summary>
        internal static string ErrorUnattendedBrokerCredentials {
            get {
                return ResourceManager.GetString("ErrorUnattendedBrokerCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoints of snapshot {0} need to be repaired yet.
        /// </summary>
        internal static string ErrorUnreparedCheckpoints {
            get {
                return ResourceManager.GetString("ErrorUnreparedCheckpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot {0} contains following checkpoint errors:{1}.
        /// </summary>
        internal static string MsgCheckpointErrors {
            get {
                return ResourceManager.GetString("MsgCheckpointErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up snaphot {0}.
        /// </summary>
        internal static string MsgCmdStart {
            get {
                return ResourceManager.GetString("MsgCmdStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inconsitences found and fixed in snapshot {1}, creating checkpoint #{2} (don&apos;t forget to push it).
        /// </summary>
        internal static string MsgCmdSuccess {
            get {
                return ResourceManager.GetString("MsgCmdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot {0} clean-up complete.
        /// </summary>
        internal static string MsgCmdSuccessNoop {
            get {
                return ResourceManager.GetString("MsgCmdSuccessNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot file for grain {0:D} seems to be corrupt.
        /// </summary>
        internal static string MsgCorruptGrain {
            get {
                return ResourceManager.GetString("MsgCorruptGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} ({1}) is marked as deleted but snapshot file still exists.
        /// </summary>
        internal static string MsgDanglingGrain {
            get {
                return ResourceManager.GetString("MsgDanglingGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} ({1}) is not listed in any snapshot checkpoint.
        /// </summary>
        internal static string MsgOrphanGrain {
            get {
                return ResourceManager.GetString("MsgOrphanGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Checkpoint file(s) #{0} is/are missing.
        /// </summary>
        internal static string MsgPartCheckpointsMissing {
            get {
                return ResourceManager.GetString("MsgPartCheckpointsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Checkpoint file #{0} for latest push is missing.
        /// </summary>
        internal static string MsgPartLastPushedMissing {
            get {
                return ResourceManager.GetString("MsgPartLastPushedMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Latest checkpoint is not registered in the snapshot.
        /// </summary>
        internal static string MsgPartLatestCheckpointNotRegistered {
            get {
                return ResourceManager.GetString("MsgPartLatestCheckpointNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Local checkpoint file #{0} is missing.
        /// </summary>
        internal static string MsgPartLocalCheckpointMissing {
            get {
                return ResourceManager.GetString("MsgPartLocalCheckpointMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning grains.
        /// </summary>
        internal static string StatuScanningGrains {
            get {
                return ResourceManager.GetString("StatuScanningGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating missing checkpoint #{0}.
        /// </summary>
        internal static string StatusCreateMissingCheckpoint {
            get {
                return ResourceManager.GetString("StatusCreateMissingCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting grain {0:D} ({1}).
        /// </summary>
        internal static string StatusDeleteGrain {
            get {
                return ResourceManager.GetString("StatusDeleteGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking grain {0:D} as deleted.
        /// </summary>
        internal static string StatusGrainMarkDeleted {
            get {
                return ResourceManager.GetString("StatusGrainMarkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling grain {0:D}.
        /// </summary>
        internal static string StatusPullGrain {
            get {
                return ResourceManager.GetString("StatusPullGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering latest checkpoint #{0} with the snapshot.
        /// </summary>
        internal static string StatusRegisterLatestCheckpoint {
            get {
                return ResourceManager.GetString("StatusRegisterLatestCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering checkpoint #{0} as latest push.
        /// </summary>
        internal static string StatusRepairLastPushed {
            get {
                return ResourceManager.GetString("StatusRepairLastPushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring local checkpoint as #{0}.
        /// </summary>
        internal static string StatusRestoreLocalCheckpoint {
            get {
                return ResourceManager.GetString("StatusRestoreLocalCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning checkpoints.
        /// </summary>
        internal static string StatusScanningCheckpoints {
            get {
                return ResourceManager.GetString("StatusScanningCheckpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In unattended mode no questions are asked, all clean-ups that can be applied safely without interactions will be applied.
        /// </summary>
        internal static string UnattendedOptionDesc {
            get {
                return ResourceManager.GetString("UnattendedOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} not found in {1}.
        /// </summary>
        internal static string WarnGrainNotFound {
            get {
                return ResourceManager.GetString("WarnGrainNotFound", resourceCulture);
            }
        }
    }
}
