//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftedSolutions.MarBasGleaner.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiffCmdL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiffCmdL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftedSolutions.MarBasGleaner.Commands.DiffCmdL10n", typeof(DiffCmdL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows differences between grains in snapshot and MarBas broker.
        /// </summary>
        internal static string CmdDesc {
            get {
                return ResourceManager.GetString("CmdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load grain {0:D} from {1}.
        /// </summary>
        internal static string ErrorGrainLoad {
            get {
                return ResourceManager.GetString("ErrorGrainLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing second grain ID for comparison mode {0}.
        /// </summary>
        internal static string ErrorMissingGrainID {
            get {
                return ResourceManager.GetString("ErrorMissingGrainID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the grain to use as comparison base, single argument version compares snapshot with broker, 2 different IDs indicate snapshot version of both by defaulft (s. --mode option).
        /// </summary>
        internal static string IdArgDesc {
            get {
                return ResourceManager.GetString("IdArgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison mode applied to grains identified by &lt;grain-ids&gt; argument, {0} is automatic mode for single ID, {1} - for 2 distinct IDs.
        /// </summary>
        internal static string ModeArgDesc {
            get {
                return ResourceManager.GetString("ModeArgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing grain {0:D} ({1}) to {2:D} ({3}).
        /// </summary>
        internal static string MsgCmdStart {
            get {
                return ResourceManager.GetString("MsgCmdStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing grain {0:D} ({1}) to itself ({3}).
        /// </summary>
        internal static string MsgCmdStartSameID {
            get {
                return ResourceManager.GetString("MsgCmdStartSameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grains are identical.
        /// </summary>
        internal static string MsgCmdSuccessNoop {
            get {
                return ResourceManager.GetString("MsgCmdSuccessNoop", resourceCulture);
            }
        }
    }
}
