//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarBasGleaner.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoCmdL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoCmdL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarBasGleaner.Commands.InfoCmdL10n", typeof(InfoCmdL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays general information about a snapshot.
        /// </summary>
        internal static string CmdDesc {
            get {
                return ResourceManager.GetString("CmdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked.
        /// </summary>
        internal static string ConnectionStatusUnknown {
            get {
                return ResourceManager.GetString("ConnectionStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active checkpoint:     {0:D4} ({1}).
        /// </summary>
        internal static string InfoActiveCheckpoint {
            get {
                return ResourceManager.GetString("InfoActiveCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancor Grain:       {0:D} ({1}).
        /// </summary>
        internal static string InfoAnchor {
            get {
                return ResourceManager.GetString("InfoAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Grain:      {0} (missing).
        /// </summary>
        internal static string InfoAnchorMissing {
            get {
                return ResourceManager.GetString("InfoAnchorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API version:        {0}.
        /// </summary>
        internal static string InfoConnectionAPIVersion {
            get {
                return ResourceManager.GetString("InfoConnectionAPIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication:     {0}.
        /// </summary>
        internal static string InfoConnectionAuth {
            get {
                return ResourceManager.GetString("InfoConnectionAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker instance ID: {0:D}.
        /// </summary>
        internal static string InfoConnectionInstanceID {
            get {
                return ResourceManager.GetString("InfoConnectionInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema version:     {0}.
        /// </summary>
        internal static string InfoConnectionSchemaVersion {
            get {
                return ResourceManager.GetString("InfoConnectionSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:             {0}.
        /// </summary>
        internal static string InfoConnectionStatus {
            get {
                return ResourceManager.GetString("InfoConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker URL:         {0}.
        /// </summary>
        internal static string InfoConnectionURL {
            get {
                return ResourceManager.GetString("InfoConnectionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of checkpoints: {0}.
        /// </summary>
        internal static string InfoNumberCheckpoints {
            get {
                return ResourceManager.GetString("InfoNumberCheckpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushed checkpoint:     {0:D4}.
        /// </summary>
        internal static string InfoPushedCheckpoint {
            get {
                return ResourceManager.GetString("InfoPushedCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema version:    {0}.
        /// </summary>
        internal static string InfoShanshotSchemaVersion {
            get {
                return ResourceManager.GetString("InfoShanshotSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared checkpoint:     {0:D4} ({1}).
        /// </summary>
        internal static string InfoSharedCheckpoint {
            get {
                return ResourceManager.GetString("InfoSharedCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source checkpoint: {0:D4}.
        /// </summary>
        internal static string InfoSnapshotCheckpoint {
            get {
                return ResourceManager.GetString("InfoSnapshotCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope:             {0}.
        /// </summary>
        internal static string InfoSnapshotScope {
            get {
                return ResourceManager.GetString("InfoSnapshotScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:      {0}.
        /// </summary>
        internal static string InfoSnapshotUpdated {
            get {
                return ResourceManager.GetString("InfoSnapshotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:           {0}.
        /// </summary>
        internal static string InfoSnapshotVersion {
            get {
                return ResourceManager.GetString("InfoSnapshotVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection properties.
        /// </summary>
        internal static string MsgHeadConnection {
            get {
                return ResourceManager.GetString("MsgHeadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot properties.
        /// </summary>
        internal static string MsgHeadSnapshot {
            get {
                return ResourceManager.GetString("MsgHeadSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization info.
        /// </summary>
        internal static string MsgHeadSynchronization {
            get {
                return ResourceManager.GetString("MsgHeadSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string MsgNotConnected {
            get {
                return ResourceManager.GetString("MsgNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate connection and compatibility to MarBas broker.
        /// </summary>
        internal static string ValidateConnectionDesc {
            get {
                return ResourceManager.GetString("ValidateConnectionDesc", resourceCulture);
            }
        }
    }
}
