//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarBasGleaner.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PullCmdL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PullCmdL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarBasGleaner.Commands.PullCmdL10n", typeof(PullCmdL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please decide how to procede{0}   1. Keep snapshot version as current{0}   2. Overwrite snapshot grain with the broker version{0}   3. Save broker version into a temporary file and resolve conflict manually{0}   4. Display differences and decide again.
        /// </summary>
        internal static string ChoiceGrainConflict {
            get {
                return ResourceManager.GetString("ChoiceGrainConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulls modified and new grains from MarBas broker into snapshot.
        /// </summary>
        internal static string CmdDesc {
            get {
                return ResourceManager.GetString("CmdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new checkpoint even when it&apos;s safe using latest existing one.
        /// </summary>
        internal static string ForceCheckpointOptionDesc {
            get {
                return ResourceManager.GetString("ForceCheckpointOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an option 1-4.
        /// </summary>
        internal static string MsgChooseOf4 {
            get {
                return ResourceManager.GetString("MsgChooseOf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling grains from {0} into snapshot {1}.
        /// </summary>
        internal static string MsgCmdStart {
            get {
                return ResourceManager.GetString("MsgCmdStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated {0} changes into checkpont {1} of snapshot {2}.
        /// </summary>
        internal static string MsgCmdSuccess {
            get {
                return ResourceManager.GetString("MsgCmdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot {0} is already uptodate.
        /// </summary>
        internal static string MsgCmdSuccessNoop {
            get {
                return ResourceManager.GetString("MsgCmdSuccessNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always overwrite grains even newer ones when pulling into snapshot.
        /// </summary>
        internal static string OverwriteOptionDesc {
            get {
                return ResourceManager.GetString("OverwriteOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both versions of grain {0:D} ({1}) have been modified (snapshot timestamp: {2:O}, broker timestamp: {3:O}).
        /// </summary>
        internal static string StatusGrainConflict {
            get {
                return ResourceManager.GetString("StatusGrainConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping deleted grain {0:D}.
        /// </summary>
        internal static string StatusGrainDeleted {
            get {
                return ResourceManager.GetString("StatusGrainDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling missing grain {0:D} ({1}).
        /// </summary>
        internal static string StatusGrainPull {
            get {
                return ResourceManager.GetString("StatusGrainPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging deleted grain {0:D} ({1}).
        /// </summary>
        internal static string StatusGrainPurge {
            get {
                return ResourceManager.GetString("StatusGrainPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} stored to {1}.
        /// </summary>
        internal static string StatusGrainStored {
            get {
                return ResourceManager.GetString("StatusGrainStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating grain {0:D} ({1}).
        /// </summary>
        internal static string StatusGrainUpdate {
            get {
                return ResourceManager.GetString("StatusGrainUpdate", resourceCulture);
            }
        }
    }
}
