//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarBasGleaner.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PushCmdL10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushCmdL10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarBasGleaner.Commands.PushCmdL10n", typeof(PushCmdL10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushes most recent grains from snapshot into MarBas broker.
        /// </summary>
        internal static string CmdDesc {
            get {
                return ResourceManager.GetString("CmdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker {0} refused to perform push request.
        /// </summary>
        internal static string ErrorBrokerRequest {
            get {
                return ResourceManager.GetString("ErrorBrokerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to store {0} / delete {1} grains in {2}: {3}.
        /// </summary>
        internal static string ErrorBrokerRequestException {
            get {
                return ResourceManager.GetString("ErrorBrokerRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing grains from snapshot {0} to {1}.
        /// </summary>
        internal static string MsgCmdStart {
            get {
                return ResourceManager.GetString("MsgCmdStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully stored {0} / deleted {1} grains in {2}.
        /// </summary>
        internal static string MsgCmdSuccess {
            get {
                return ResourceManager.GetString("MsgCmdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest checkpoint {0} has already been pushed.
        /// </summary>
        internal static string MsgCmdSuccessNoop {
            get {
                return ResourceManager.GetString("MsgCmdSuccessNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint number to start operation with, -1 for latest.
        /// </summary>
        internal static string StartingCheckpointOptionDesc {
            get {
                return ResourceManager.GetString("StartingCheckpointOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grains queued for deletion:.
        /// </summary>
        internal static string StatusQueueDelete {
            get {
                return ResourceManager.GetString("StatusQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grains queued for submission:.
        /// </summary>
        internal static string StatusQueueStore {
            get {
                return ResourceManager.GetString("StatusQueueStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy for handling grains existing on both sides - in the snapshot and broker.
        /// </summary>
        internal static string StrategyOptionDesc {
            get {
                return ResourceManager.GetString("StrategyOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored {0} / deleted {1} grains in {2} with warnings / errors.
        /// </summary>
        internal static string WarnCmdResult {
            get {
                return ResourceManager.GetString("WarnCmdResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain {0:D} not found in snapshot, correcting checkpoint {1}.
        /// </summary>
        internal static string WarnGrainNotFound {
            get {
                return ResourceManager.GetString("WarnGrainNotFound", resourceCulture);
            }
        }
    }
}
