
name: Publish Main Release

on:
  release:
    types: [published]

env:
    PROJECT_NAME: MarBasGleaner

jobs:

  release:
    name: Release
    strategy:
      matrix:
        kind: ['portable', 'linux', 'windows', 'macOS', 'macOSIntel']
        include:
          - kind: portable
            os: ubuntu-latest
            target: portable
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-arm64
          - kind: macOSIntel
            os: macos-latest
            target: osx-x64

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # - name: Verify commit exists in origin/main
    #   run: |
    #     git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    #     git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      shell: bash
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      shell: bash
      run: |
        dotnet publish src/${PROJECT_NAME}/${PROJECT_NAME}.csproj -p:PublishProfile=${{ matrix.target }} -p:Version=${VERSION}

        if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${PROJECT_NAME}-${VERSION}-${{ matrix.target }}.zip" "./distr/${{ matrix.target }}/*"
        else
            tar czvf "${PROJECT_NAME}-${VERSION}-${{ matrix.target }}.tar.gz" -C "./distr/${{ matrix.target }}" .
        fi

    - name: Publish to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: "${{ env.PROJECT_NAME }}-${{ env.VERSION }}-*"
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
